# Generated by Django 2.0 on 2017-12-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0003_auto_20171220_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deputados',
            options={'managed': True, 'verbose_name': 'deputado', 'verbose_name_plural': 'deputados'},
        ),
    ]
