# Generated by Django 2.0 on 2017-12-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0007_deputados_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputados',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deputados',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deputados',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deputados',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
