# Generated by Django 2.0 on 2017-12-09 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_partido', models.IntegerField()),
                ('nome_partido', models.CharField(max_length=50)),
                ('sigla_partido', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='deputado',
            name='foto',
            field=models.ImageField(default='', upload_to='deputados_perfil/'),
        ),
        migrations.AddField(
            model_name='deputado',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deputado',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alba.Partido'),
        ),
    ]
