# Generated by Django 2.0 on 2017-12-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0002_auto_20171209_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Deputados',
            fields=[
                ('id_deputado', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('partido', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=15, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'deputados',
                'verbose_name': 'deputado',
                'verbose_name_plural': 'deputados',
            },
        ),
        migrations.CreateModel(
            name='GastoMensal',
            fields=[
                ('mes', models.IntegerField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('id_deputado', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'gasto_mensal',
            },
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id_partido', models.IntegerField(primary_key=True, serialize=False)),
                ('id_deputado', models.IntegerField()),
                ('nome_partido', models.CharField(blank=True, max_length=256, null=True)),
                ('sigla', models.CharField(blank=True, max_length=48, null=True)),
                ('numero_legenda', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'partidos',
                'verbose_name': 'partido',
                'verbose_name_plural': 'partidos',
            },
        ),
        migrations.RemoveField(
            model_name='deputado',
            name='partido',
        ),
        migrations.DeleteModel(
            name='Deputado',
        ),
        migrations.DeleteModel(
            name='Partido',
        ),
    ]
