# Generated by Django 2.0 on 2017-12-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0004_auto_20171221_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputados',
            name='biografia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='deputados',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deputados',
            name='endereco',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deputados',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deputados',
            name='telefone',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='deputados',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deputados',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deputados',
            name='slug',
            field=models.SlugField(max_length=25, unique=True),
        ),
    ]
