# Generated by Django 2.0 on 2017-12-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0005_auto_20171221_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputados',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deputados',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deputados',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deputados',
            name='telefone',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='deputados',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
