# Generated by Django 2.0 on 2017-12-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0008_auto_20171221_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputados',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
