# Generated by Django 2.0 on 2017-12-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0009_deputados_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputados',
            name='telefone',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
