# Generated by Django 2.0 on 2017-12-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0010_auto_20171222_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputados',
            name='mandato_atual',
            field=models.BooleanField(default=True),
        ),
    ]
