# Generated by Django 2.0 on 2017-12-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alba', '0011_deputados_mandato_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputados',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
